name: need_help
description: Projeto para ver e salvar passo-a-passos.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  sqflite:

  cupertino_icons: ^1.0.2

  google_fonts: ^3.0.1

dev_dependencies:
  test:
  flutter_test:
    sdk: flutter
  sqflite_common_ffi:

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/